apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ai
  namespace: local-ai
  labels:
    app: local-ai
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi